export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE'
export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST'
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'

export const FETCH_MOVIE_FAILURE = 'FETCH_MOVIE_FAILURE'
export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST'
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS'

export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'

export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE'
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
